spring.application.name: config-server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anuj-Kumar-Sharma/ecommerce-config-server
          username: ${GITHUB_USERNAME:anuj-kumar-sharma}
          password: ${GITHUB_TOKEN}
          default-label: master
server:
  port: 8888
